# Generated by Django 4.0.4 on 2022-04-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('width1', models.BooleanField(default=True)),
                ('width2', models.BooleanField(default=False)),
                ('height', models.BooleanField(default=True)),
                ('diameter1', models.BooleanField(default=True)),
                ('diameter2', models.BooleanField(default=False)),
                ('volume', models.BooleanField(default=False)),
                ('weight', models.BooleanField(default=True)),
                ('density', models.IntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
                ('Formula', models.CharField(blank=True, max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StandardPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwg_no', models.IntegerField()),
                ('rev', models.CharField(max_length=200)),
                ('det_no', models.CharField(max_length=250)),
                ('Manufacturer', models.CharField(max_length=250)),
                ('model_no', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=200)),
                ('currency_sgd', models.FloatField()),
                ('price_sgd', models.FloatField()),
                ('total_price_sgd', models.FloatField()),
            ],
        ),
    ]
