# Generated by Django 4.0.4 on 2022-04-25 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_adminmaterial_formula'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminMaterial',
            new_name='Material',
        ),
    ]
