# Generated by Django 4.0.4 on 2022-05-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_adminmaterial_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Formula',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(choices=[('Material 1', 'Material 1'), ('Material 2', 'Material 2'), ('Material 3', 'Material 4'), ('Material 4', 'Material 4')], max_length=200),
        ),
    ]
