# Generated by Django 4.0.4 on 2022-05-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_material_formula_alter_material_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Material 1', 'Material 1'), ('Material 2', 'Material 2'), ('Material 3', 'Material 4'), ('Material 4', 'Material 4')], max_length=200)),
                ('width1', models.BooleanField(default=True)),
                ('width2', models.BooleanField(default=False)),
                ('height', models.BooleanField(default=True)),
                ('diameter1', models.BooleanField(default=True)),
                ('diameter2', models.BooleanField(default=False)),
                ('volume', models.BooleanField(default=False)),
                ('weight', models.BooleanField(default=True)),
                ('density', models.IntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
                ('Formula', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='material',
            name='Formula',
        ),
        migrations.AlterField(
            model_name='material',
            name='density',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='diameter1',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='diameter2',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='height',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='volume',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='weight',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='width1',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='width2',
            field=models.FloatField(blank=True),
        ),
    ]
