# Generated by Django 4.0.4 on 2022-05-06 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_materialconfiguration_remove_material_formula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_no', models.CharField(max_length=300, unique=True)),
                ('dwg_no', models.CharField(max_length=300)),
                ('customer', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('editor', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
