# Generated by Django 4.0.4 on 2022-05-06 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rfqentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='rfq_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.rfqentry'),
        ),
    ]
