# Generated by Django 4.0.4 on 2022-05-07 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_material_rfq_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialconfiguration',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material'),
        ),
    ]
