# Generated by Django 4.0.4 on 2022-05-09 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_materialconfiguration_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='rfq_no',
        ),
        migrations.CreateModel(
            name='ProcessCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True)),
                ('primary_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.primaryprocess')),
                ('rfq_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.rfqentry')),
                ('secondary_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.secondaryprocess')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.material')),
                ('rfq_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.rfqentry')),
            ],
        ),
    ]
