# Generated by Django 4.0.4 on 2022-05-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_material_rfq_no_processcost_materialcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='density',
        ),
        migrations.RemoveField(
            model_name='material',
            name='diameter1',
        ),
        migrations.RemoveField(
            model_name='material',
            name='diameter2',
        ),
        migrations.RemoveField(
            model_name='material',
            name='height',
        ),
        migrations.RemoveField(
            model_name='material',
            name='price',
        ),
        migrations.RemoveField(
            model_name='material',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='material',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='material',
            name='width1',
        ),
        migrations.RemoveField(
            model_name='material',
            name='width2',
        ),
        migrations.AddField(
            model_name='materialcost',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialcost',
            name='diameter1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialcost',
            name='diameter2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialcost',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialcost',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialcost',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialcost',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialcost',
            name='width1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialcost',
            name='width2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialcost',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
