# Generated by Django 4.0.4 on 2022-05-10 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0010_remove_material_density_remove_material_diameter1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcost',
            name='editor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processcost',
            name='editor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
