# Generated by Django 4.0.4 on 2022-05-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_materialcost_editor_processcost_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcost',
            name='primary_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processcost',
            name='secondary_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
